### DISCUSSION TITLE
Single Garage Door Sketch

### DISCUSSION THREAD

**Discussion by Douganatornz** [muxa/esphome-state-machine#17] [General]
@muxa
I have a very simple/standard setup.
Single garage door/motor
RF Remote
ESP8266 with single contact reply wired into motor input
Contact sensor wired to ESP8266 to show closed state

What I would like to do using this new ESPHome code is to show states CLOSED, OPENING, OPEN, CLOSING.
I guess this could be achieved by timings?
Also I would like a small delay on the contact sensor state change just because when the door is opening the state changes many times in the first second of the door opening.

Thanks

**Comment by muxa** [comment]
> CLOSED, OPENING, OPEN, CLOSING

Does this mean that if you press the button while the door is opening or closing it will stop and immediately reverse direction? In other words the door will never be left in a half closed/open state?

> I would like a small delay on the contact sensor state change

This can easily be achieved with a `delayed_on` [filter on the binary_sensor](https://esphome.io/components/binary_sensor/index.html?highlight=binary_sensor#delayed-on)

**Reply by Douganatornz** [reply]
> 
> 
> > CLOSED, OPENING, OPEN, CLOSING
> 
> Does this mean that if you press the button while the door is opening or closing it will stop and immediately reverse direction? In other words the door will never be left in a half closed/open state?
> 
> > I would like a small delay on the contact sensor state change
> 
> This can easily be achieved with a `delayed_on` [filter on the binary_sensor](https://esphome.io/components/binary_sensor/index.html?highlight=binary_sensor#delayed-on)

No, I would like a delay for the contact sensor state change. As the sensor is moving over the magnet the state changes multiple times in 2 seconds. So, something that tells the sensor state that it hasn't changed unless the XX amount of seconds if this makes sense.

**Reply by muxa** [reply]
If I understood correctly, the above mentioned `delayed_on` (or `delayed_on_off`) will achieve what you want. It will act as a debouncer and instead of toggling on and off the sensors multiple times a second, it will only do it once in a given time:

```yaml
binary_sensor:
  - platform: gpio
    filters:
      - delayed_on_off: 2s
```

The other questions still remains:

> CLOSED, OPENING, OPEN, CLOSING

Does this mean that if you press the button while the door is opening or closing it will stop and immediately reverse direction? In other words the door will never be left in a half closed/open state?

**Reply by Douganatornz** [reply]
Yes, denouncing is the thing I’m talking about :-)

Door will never be left in a half closed/open state but, if it was it would just show as state OPEN?
If the button is pressed while the door is closing, the door will automatically raise to the open position as this is a safety feature.

**Reply by muxa** [reply]
> Door will never be left in a half closed/open state but, if it was it would just show as state OPEN?

That's one way. I prefer to have a use a separate state for when the door is stuck in a mid position (and indicate that there's a problem via separate `binary_sensor`), but that's not really necessary. 

For your use case the config will be something like this:

```yaml
binary_sensor:
  - platform: gpio
    name: "Garage Door Contact"
    pin: <PIN>
    id: closed_endstop
    on_press: # garage is open(ing)      
      - state_machine.transition: OPENING_DETECTED
    on_release: # garage is closed
      - state_machine.transition: CLOSED_DETECTED
    filters:
      - delayed_on_off: 2s
      
switch:
  - platform: gpio
    pin:<PIN>
    id: garage_opener_relay
    internal: true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: garage_opener_relay

state_machine:
  - name: Garage Door State Machine
    id: garage_sm
    states:
      - name: CLOSED
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: CLOSED
              current_operation: IDLE
      - name: OPENING
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: OPENING
          - delay: 16s # match gate opening time
          - state_machine.transition: TIMEOUT
      - name: OPEN
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: IDLE
      - name: CLOSING
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: CLOSING
          - delay: 17s # match actual closing time + 1s
          - state_machine.transition: TIMEOUT
    inputs:
      - name: TIMEOUT
        transitions:
          - OPENING -> OPEN
          - CLOSING -> OPEN # not detected closed using contact sensor, so the door is still open
      - name: OPENING_DETECTED
        transitions:
          - CLOSED -> OPENING
      - name: CLOSED_DETECTED
        transitions:
          - CLOSING -> CLOSED
          - OPEN -> CLOSED
          - OPENING -> CLOSED
      - name: OPEN # triggered by HA
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> OPENING
        action:
          - switch.turn_on: garage_opener_relay
      - name: CLOSE # triggered by HA
        transitions:
          - OPEN -> CLOSING
          - OPENING -> CLOSING
        action:
          - switch.turn_on: garage_opener_relay
    diagram: true

cover:
  - platform: template
    name: "Garage Door"
    id: garage_door
    device_class: garage
    lambda: |-
      if (id(garage_sm).current_state().compare("CLOSED") == 0) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    open_action: 
      - state_machine.transition: OPEN
    close_action:
      - state_machine.transition: CLOSE
```

**Reply by muxa** [reply]
@Douganatornz I think it might be simpler to not use a state machine in your case actually. 

```yaml
binary_sensor:
  - platform: gpio
    name: "Garage Door Contact"
    pin: <PIN>
    id: closed_endstop
    filters:
      - delayed_on_off: 2s
      
switch:
  - platform: gpio
    pin:<PIN>
    id: garage_opener_relay
    internal: true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: garage_opener_relay

cover:
  - platform: template
    name: "Garage Door"
    id: garage_door
    device_class: garage
    lambda: |-
      if (id(closed_endstop).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action: 
      - switch.turn_on: garage_opener_relay
    close_action:
      - switch.turn_on: garage_opener_relay
```
