### DISCUSSION TITLE
Single garage door: Relay (to toggle) + Open sensor + Closed sensor + toggle button

### DISCUSSION THREAD

**Discussion by alnavasa** [muxa/esphome-state-machine#22] [Ideas]
Hi muxa, Ive read many of your comments, and I am going to attempt to build the code for the setup I have

It is a garage door with a button to toggle the action, 
To mimic that I have already developed this code with a push button sensor and a relay:

```
switch:
  - platform: gpio
    pin: GPIO13
    name: "Abridor Puerta Coches"
    icon: mdi:door-closed
    restore_mode: always_off
    id: r1
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: r1




binary_sensor:
  - platform: gpio
    name: Mando RF puerta coches
    filters:
      - delayed_on: 100ms

    pin:
      number: GPIO14
#      mode: INPUT_PULLUP
      inverted: True
    id: Remote
    on_press:
      - switch.turn_on: r1
      - delay: 300ms
      - switch.turn_off: r1
      
```

I have two sensors for the two states of the door:
```

  - platform: gpio
    pin:
      number: GPIO12
#      mode: INPUT_PULLUP
      inverted: true
    id: endstop_opened
    name: Sensor puerta coches abierta
    filters:
      - delayed_on: 100ms
    
    



    
  - platform: gpio
    pin:
      number: GPIO5
#      mode: INPUT_PULLUP
      inverted: true
    id: endstop_closed
    name: Sensor puerta coches cerrada
    filters:
      - delayed_on: 100ms


```

I will try state machine to implement a proper cover setup (with positioning and %positioning) for this installation and I'll keep the progress here, 
any help would be appreciated

Thanks!

**Comment by alnavasa** [comment]
I gave it a try, but its in a boot loop, I don't know why,
Here is the code and the error:

@muxa Can you please point me where to point towards to?, thanks!

```
substitutions:
  node_name: test-bench
  device_name: Test Bench


esphome:
  name: $node_name
  comment: $device_name

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$node_name"
    password: !secret fallback_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine

text_sensor:
  - platform: template
    name: Uptime $device_name
    id: uptime_human
    entity_category: diagnostic
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: $device_name IP
    ssid:
      name: $device_name SSID
    bssid:
      name: $device_name BSSID









state_machine:
  - name: Garage Door State Machine
    id: garage_sm
    states:
      - name: CLOSED

      - name: OPENING
        on_enter:
          - delay: 16s
          - state_machine.transition: TIMEOUT
      - name: OPEN

      - name: OPENING_INTERRUPTED

      - name: CLOSING
        on_enter:

          - delay: 16s
          - state_machine.transition: TIMEOUT
      - name: CLOSING_INTERRUPTED

    inputs:
      - name: PRESS
        transitions:
          - CLOSED -> OPENING
          - OPENING -> OPENING_INTERRUPTED
          - OPENING_INTERRUPTED -> CLOSING
          - OPEN -> CLOSING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING
      - name: TIMEOUT
        transitions:
          - OPENING -> OPEN
          - CLOSING -> CLOSED
      - name: OPENING_DETECTED
        transitions:
          - CLOSED -> OPENING
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSING -> OPENING
          - OPENING_INTERRUPTED -> OPENING
          - CLOSING_INTERRUPTED -> OPENING
      - name: CLOSED_DETECTED
        transitions:
          - CLOSING -> CLOSED
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPEN -> CLOSED
          - OPENING -> CLOSED
          - OPENING_INTERRUPTED -> CLOSED
          - CLOSING_INTERRUPTED -> CLOSED

      - name: CLOSING_DETECTED
        transitions:
          - OPEN -> CLOSING
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPENING -> CLOSING
          - CLOSING_INTERRUPTED -> CLOSING
          - OPENING_INTERRUPTED -> CLOSING
      - name: OPEN_DETECTED
        transitions:
          - OPENING -> OPEN
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSED -> OPEN
          - CLOSING -> OPEN
          - CLOSING_INTERRUPTED -> OPEN
          - OPENING_INTERRUPTED -> OPEN




          
      - name: OPEN
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING
          - OPENING_INTERRUPTED -> CLOSING
        action:
          - switch.turn_on: r1
          - delay: 1500ms
          - state_machine.transition: OPEN
      - name: CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> OPENING_INTERRUPTED          
          - OPENING_INTERRUPTED -> CLOSING
          - CLOSING_INTERRUPTED -> OPENING
        action:
          - switch.turn_on: r1
          - delay: 1500ms
          - state_machine.transition: CLOSE
      - name: STOP
        transitions:
          - OPENING -> OPENING_INTERRUPTED
          - CLOSING -> CLOSING_INTERRUPTED
        action:
          - switch.turn_on: r1
    diagram: true




















sensor:
  - platform: wifi_signal
    name: "WiFi Signal $device_name"
    update_interval: 60s

  - platform: uptime
    name: Uptime $device_name System
    id: uptime_sensor
    update_interval: 60s
    entity_category: diagnostic
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();






#status_led:
#  pin:
#    number: GPIO2






###################

button:

  - platform: restart
    name: "$device_name Restart"
switch:

  - platform: gpio
    pin: GPIO13
    name: "Abridor Puerta Coches_TEST"
    icon: mdi:gate
    restore_mode: always_off
    id: r1
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: r1




binary_sensor:
  - platform: gpio
    name: Mando RF puerta coches_TEST
    filters:
      - delayed_on: 100ms

    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: Remote
    on_press:
      - switch.turn_on: r1
      - state_machine.transition: PRESS
      - delay: 300ms
      - switch.turn_off: r1



    
    
    
    


  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    id: endstop_opened
    name: Sensor puerta coches abierta_TEST
    filters:
      - delayed_on: 100ms
    

    on_press: # garage is open(ing)      
      - state_machine.transition: OPENING_DETECTED
    on_release: # garage is closed
      - state_machine.transition: CLOSED_DETECTED


    


    
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    id: endstop_closed
    name: Sensor puerta coches cerrada_TEST
    filters:
      - delayed_on: 100ms

    on_press: # garage is clos(ing)      
      - state_machine.transition: CLOSING_DETECTED
    on_release: # garage is open
      - state_machine.transition: OPEN_DETECTED



  - platform: status
    name: "Status $device_name"

















    

```




<img width="664" alt="Captura de pantalla 2022-03-21 a las 21 57 08" src="https://user-images.githubusercontent.com/458370/159362747-c421fedd-e17f-4eb0-981c-d7e46a215299.png">

**Reply by muxa** [reply]
Hey @alnavasa 
One thing I've noticed is:

```yaml
      - name: CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> OPENING_INTERRUPTED          
          - OPENING_INTERRUPTED -> CLOSING
          - CLOSING_INTERRUPTED -> OPENING
        action:
          - switch.turn_on: r1
          - delay: 1500ms
          - state_machine.transition: CLOSE
      - name: CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> OPENING_INTERRUPTED          
          - OPENING_INTERRUPTED -> CLOSING
          - CLOSING_INTERRUPTED -> OPENING
        action:
          - switch.turn_on: r1
          - delay: 1500ms
          - state_machine.transition: CLOSE
```

You should not call `state_machine.transition` using the same input inside an action. This might cause a loop. In your case I think hast having `switch.turn_on: r1` in the actions is enough (the rest will be handled by timeout, contact sensors and button)

**Reply by spacemanspiff2007** [reply]
It would be nice if this would be caught when building the code

**Reply by alnavasa** [reply]
> Hey @alnavasa One thing I've noticed is:

> You should not call `state_machine.transition` using the same input inside an action. This might cause a loop. In your case I think hast having `switch.turn_on: r1` in the actions is enough (the rest will be handled by timeout, contact sensors and button)

Okey, I am going to give that a try, I grabbed that part from here: https://gist.github.com/muxa/68a6e8f8cdbb734c9e0d06a9b87d0147

**Comment by alnavasa** [comment]
Still having a loop at the boot:

```
substitutions:
  node_name: test-bench
  device_name: Test Bench


esphome:
  name: $node_name
  comment: $device_name

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$node_name"
    password: !secret fallback_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine

text_sensor:
  - platform: template
    name: Uptime $device_name
    id: uptime_human
    entity_category: diagnostic
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: $device_name IP
    ssid:
      name: $device_name SSID
    bssid:
      name: $device_name BSSID









state_machine:
  - name: Garage Door State Machine
    id: garage_sm
    states:
      - name: CLOSED

      - name: OPENING
        on_enter:
          - delay: 16s
          - state_machine.transition: TIMEOUT
      - name: OPEN

      - name: OPENING_INTERRUPTED

      - name: CLOSING
        on_enter:

          - delay: 16s
          - state_machine.transition: TIMEOUT
      - name: CLOSING_INTERRUPTED

    inputs:
      - name: PRESS
        transitions:
          - CLOSED -> OPENING
          - OPENING -> OPENING_INTERRUPTED
          - OPENING_INTERRUPTED -> CLOSING
          - OPEN -> CLOSING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING
      - name: TIMEOUT
        transitions:
          - OPENING -> OPEN
          - CLOSING -> CLOSED
      - name: OPENING_DETECTED
        transitions:
          - CLOSED -> OPENING
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSING -> OPENING
          - OPENING_INTERRUPTED -> OPENING
          - CLOSING_INTERRUPTED -> OPENING
      - name: CLOSED_DETECTED
        transitions:
          - CLOSING -> CLOSED
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPEN -> CLOSED
          - OPENING -> CLOSED
          - OPENING_INTERRUPTED -> CLOSED
          - CLOSING_INTERRUPTED -> CLOSED

      - name: CLOSING_DETECTED
        transitions:
          - OPEN -> CLOSING
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPENING -> CLOSING
          - CLOSING_INTERRUPTED -> CLOSING
          - OPENING_INTERRUPTED -> CLOSING
      - name: OPEN_DETECTED
        transitions:
          - OPENING -> OPEN
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSED -> OPEN
          - CLOSING -> OPEN
          - CLOSING_INTERRUPTED -> OPEN
          - OPENING_INTERRUPTED -> OPEN




          
      - name: OPEN
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING
          - OPENING_INTERRUPTED -> CLOSING
        action:
          - switch.turn_on: r1

      - name: CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> OPENING_INTERRUPTED          
          - OPENING_INTERRUPTED -> CLOSING
          - CLOSING_INTERRUPTED -> OPENING
        action:
          - switch.turn_on: r1

      - name: STOP
        transitions:
          - OPENING -> OPENING_INTERRUPTED
          - CLOSING -> CLOSING_INTERRUPTED
        action:
          - switch.turn_on: r1
    diagram: true




















sensor:
  - platform: wifi_signal
    name: "WiFi Signal $device_name"
    update_interval: 60s

  - platform: uptime
    name: Uptime $device_name System
    id: uptime_sensor
    update_interval: 60s
    entity_category: diagnostic
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();






status_led:
  pin:
    number: GPIO2






###################

button:

  - platform: restart
    name: "$device_name Restart"
switch:

  - platform: gpio
    pin: GPIO13
    name: "Abridor Puerta Coches_TEST"
    icon: mdi:gate
    restore_mode: always_off
    id: r1
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: r1




binary_sensor:
  - platform: gpio
    name: Mando RF puerta coches_TEST
    filters:
      - delayed_on: 100ms

    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: Remote
    on_press:
      - switch.turn_on: r1
      - state_machine.transition: PRESS
      - delay: 300ms
      - switch.turn_off: r1



    
    
    
    


  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    id: endstop_opened
    name: Sensor puerta coches abierta_TEST
    filters:
      - delayed_on: 100ms
    

    on_press: # garage is open(ing)      
      - state_machine.transition: OPENING_DETECTED
    on_release: # garage is closed
      - state_machine.transition: CLOSED_DETECTED


    


    
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    id: endstop_closed
    name: Sensor puerta coches cerrada_TEST
    filters:
      - delayed_on: 100ms

    on_press: # garage is open(ing)      
      - state_machine.transition: CLOSING_DETECTED
    on_release: # garage is closed
      - state_machine.transition: OPEN_DETECTED



  - platform: status
    name: "Status $device_name"

















    

```
<img width="653" alt="Captura de pantalla 2022-03-22 a las 9 34 53" src="https://user-images.githubusercontent.com/458370/159440053-583f16c7-58d1-4b4b-8eb1-7cfe4f171ec4.png">

**Reply by alnavasa** [reply]
Re working on the project, two endstops for the setup plus one button. State machine diagram as follows:

![image](https://user-images.githubusercontent.com/458370/189501637-4592a061-4c39-47b4-bda2-2331a026fbc0.png)

**Reply by alnavasa** [reply]
This new "feedback cover" might be exactly what we want?
No need for state machine?
Released august 17th 


ESPHome:

https://esphome.io/components/cover/feedback.html


@muxa

**Reply by muxa** [reply]
I have not looked at the feedback cover yet, but if it does the job without the need for a state machine that would be great (simpler is better)

**Reply by dasdundave** [reply]
I've tried the feedback cover after reading about it here. **It didn't work well for me.**

- When garagedoor is controlled manually, there is no opening/closing state.
- The positioning control does not work as expected, since it doens't know the door has single pulse control.
- The stop action needs additonal if statements. In this config it would activate the relay when the door is open or closed.

This was my testing config:
```
cover:
  - platform: feedback
    name: None
    id: garage_door
    device_class: garage

    assumed_state: True

    has_built_in_endstop: True # Indicates that the cover has built in end stop detectors. In this configuration the stop_action is not performed when the open or close time is completed and if the cover is commanded to open or close the corresponding actions will be performed without checking current state. 
    # max_duration: 23s # The maximum duration the cover should be opening or closing. Useful for protecting from dysfunctional endstops.
    # --> Dsiabled max_duration, when it was reached it would control the stop_action dispite has_built_in_endstop is set to True
    direction_change_wait_time: 2s # Stops cover and forces a wait time between changes in direction

    open_action:
      - switch.turn_on: garage_switch
    open_duration: 18s
    open_endstop: open_endstop

    close_action:
      - switch.turn_on: garage_switch
    close_duration: 18s
    close_endstop: closed_endstop

    stop_action:
      - switch.turn_on: garage_switch
```

My hardware setup is:
- relay for sending pulse to the motor (only 1 input on motor for pulse)
- reed switch for closed state
- reed switch for open state
- There is no press button directly attached to ESP. (The wall button is directly connected to the motor)

The motor works like this: closed > pulse > opening > pulse halfway > stop > pulse > closing

[Below in this discussion you can find my working configuration with the Muxa state machine.](https://github.com/muxa/esphome-state-machine/discussions/22#discussioncomment-7285256)

**Comment by dasdundave** [comment]
I tested different configuration found online. But this one from Muxa works perfect for my use case.

@muxa thanks for creating this brilliant state machine!

My hardware setup is:
- relay for sending pulse to the motor (only 1 input on motor for pulse)
- reed switch for closed state
- reed switch for open state
- There is no press button directly attached to ESP. (The wall button is directly connected to the motor)

The motor works like this: closed > pulse > opening > pulse halfway > stop > pulse > closing

This is my final config:

```
substitutions:
  name: "garage-dooropener"
  friendly_name: "Garage Dooropener"
  static_ip: x.x.x.x
  closing_time: "18s" # The time the garagedoor needs to fully close. Set this value slightly higher than the real time.
  opening_time: "18s" # The time the garagedoor needs to fully open. Set this value slightly higher than the real time.
  direction_change_wait_time: "2000ms"

esphome:
  name: $name
  friendly_name: $friendly_name
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  
  # This is required for hidden networks and can significantly improve connection times
  fast_connect: true
  
  # Static IP to avoid mDNS
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret ip_gateway_not
    subnet: !secret ip_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name} AP
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Wemos builtin LED
status_led:
  pin:
    number: D4 #GPIO2
    inverted: True

sensor:
  - platform: uptime
    name: Uptime
    unit_of_measurement: days
    update_interval: 1h
    accuracy_decimals: 1
    filters:
      - lambda: return x / 86400.0; # 60s * 60min * 24h
  
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: SSID
    mac_address:
      name: MAC address

button:
  - platform: restart
    name: Restart

##################################################
## GARAGE PULSE RELAY
##################################################
switch:
  # The relay connected to pins 7 & 8 of the garage door opener
  - platform: gpio
    pin:
      number: D6 # GPIO12
    restore_mode: ALWAYS_OFF
    id: garage_switch
    internal: true
    on_turn_on:
      - delay: 0.5s
      - switch.turn_off: garage_switch

##################################################
## API & ENDSTOP SENSORS 
##################################################
binary_sensor:
  - platform: status
    internal: true
    id: api_status_sensor
    name: "API Status"
    # This logic is needed in order to have a correct status after ESP startup
    # If ommitted: garage door was slightly openend > reboot ESP > status shows CLOSED instead of OPEN!
    on_press: # connected
      - logger.log: "CONNECTED"
      - delay: 1s
      - if:
          condition:
            binary_sensor.is_on: closed_endstop
          then: # closed
            - state_machine.set: CLOSED
          else: # open
            - logger.log: Garage door is open according to endstop sensor status
            - if:
                condition:
                  - state_machine.state: CLOSED
                then:
                  - state_machine.set: OPEN
    on_release: # disconnected
      - logger.log: "DISCONNECTED"
  
  # Doorsensor opened sensor - has an external 10K pullup resistor
  - platform: gpio
    pin:
      number: D5 # GPIO14
      inverted: false # The fysical sensor is NORMALLY OPEN (NO)!
    filters:
      - delayed_on_off: 100ms
    name: "Reed Switch Open"
    id: open_endstop
    on_press: # garage is open      
      - state_machine.transition: OPEN_DETECTED
    on_release: # garage is closing
      - state_machine.transition: CLOSING_DETECTED
  
  # Doorsensor closed sensor - has an external 10K pullup resistor
  - platform: gpio
    pin:
      number: D0 # GPIO16
      inverted: true # The fysical sensor is NORMALLY CLOSED (NC)!
    filters:
      - delayed_on_off: 100ms
    name: "Reed Switch Closed"
    id: closed_endstop
    on_press: # garage is closed
      - state_machine.transition: CLOSED_DETECTED
    on_release: # garage is opening
      - state_machine.transition: OPENING_DETECTED


##################################################
## STATE MACHINE
##################################################
external_components:
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine

state_machine:
  - name: State Machine
    id: garage_sm

    # DIAGRAM: diagram of the state machine will be output to the console during validation/compilation of YAML
    # diagram: mermaid # mermaid or dot (https://github.com/muxa/esphome-state-machine#diagrams)

    # STATES: The list of states that the state machine has.
    states:
      - name: CLOSED
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: CLOSED
              current_operation: IDLE
      
      - name: CLOSING
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: CLOSING
          - delay: ${closing_time} # Time it takes to CLOSE the garage door
          - state_machine.transition: TIMEOUT
      
      - name: CLOSING_INTERRUPTED
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: IDLE
      
      #####

      - name: OPEN
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: IDLE
      
      - name: OPENING
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: OPENING
          - delay: ${opening_time} # Time it takes to CLOSE the garage door
          - state_machine.transition: TIMEOUT
      
      - name: OPENING_INTERRUPTED
        on_enter:
          - cover.template.publish:
              id: garage_door
              state: OPEN
              current_operation: IDLE
    
    # INPUTS: The list of inputs that the state machine supports with allowed state transitions.
    inputs:
      - name: TIMEOUT
        transitions:
          - OPENING -> OPEN
          - CLOSING -> CLOSED
      
      #####

      - name: CLOSE
        transitions:
          - OPEN -> CLOSING
          - OPENING -> OPENING_INTERRUPTED          
          - OPENING_INTERRUPTED -> CLOSING
          - CLOSING_INTERRUPTED -> OPENING
        on_input:
          - switch.turn_on: garage_switch
          - delay: ${direction_change_wait_time} # Delay if changing direction
          - state_machine.transition: CLOSE # Returns to itself for this scenario --> OPENING > press down arrow > Relay pulse > STOPS (OPENING_INTERRUPTED) > Code comes back = pulse relay > CLOSING (further transition not allowed)
      
      - name: CLOSING_DETECTED
        transitions:
          - OPEN -> CLOSING
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPENING -> CLOSING
          - CLOSING_INTERRUPTED -> CLOSING
          - OPENING_INTERRUPTED -> CLOSING
      
      - name: CLOSED_DETECTED
        transitions:
          - CLOSING -> CLOSED
          # below is a fallback so that contact sensor can override "normal" transitions
          - OPEN -> CLOSED
          - OPENING -> CLOSED
          - OPENING_INTERRUPTED -> CLOSED
          - CLOSING_INTERRUPTED -> CLOSED

      #####

      - name: OPEN
        transitions:
          - CLOSED -> OPENING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING
          - OPENING_INTERRUPTED -> CLOSING
        on_input:
          - switch.turn_on: garage_switch
          - delay: ${direction_change_wait_time} # Delay if changing direction
          - state_machine.transition: OPEN # Returns to itself for this scenario --> CLOSING > press up arrow > Relay pulse > STOPS (CLOSING_INTERRUPTED) > Code comes back = pulse relay > OPENING (further transition not allowed)
      
      - name: OPENING_DETECTED
        transitions:
          - CLOSED -> OPENING
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSING -> OPENING
          - OPENING_INTERRUPTED -> OPENING
          - CLOSING_INTERRUPTED -> OPENING

      - name: OPEN_DETECTED
        transitions:
          - OPENING -> OPEN
          # below is a fallback so that contact sensor can override "normal" transitions
          - CLOSED -> OPEN
          - CLOSING -> OPEN
          - CLOSING_INTERRUPTED -> OPEN
          - OPENING_INTERRUPTED -> OPEN
      
      ######
      
      - name: STOP
        transitions:
          - OPENING -> OPENING_INTERRUPTED
          - CLOSING -> CLOSING_INTERRUPTED
        on_input:
          - switch.turn_on: garage_switch


##################################################
## COVER
##################################################
cover:
  - platform: template
    name: None
    id: garage_door
    device_class: garage
    assumed_state: true # If disabled --> OPEN > STOP --> only down arrow and no up arrow
    lambda: |-
      if (id(garage_sm).current_state().compare("CLOSED") == 0) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    
    open_action: 
      - logger.log: "Garage door is being opened by HA"
      - state_machine.transition: OPEN
    
    close_action:
      - logger.log: "Garage door is being closed by HA"
      - state_machine.transition: CLOSE
    
    stop_action:
      - logger.log: "Garage door is stopped by HA"
      - state_machine.transition: STOP
```
