### DISCUSSION TITLE
Code for a Shelly1 connected to a Gate or Garage door with a "closed sensor"

### DISCUSSION THREAD

**Discussion by hoontune** [muxa/esphome-state-machine#31] [Q&A]
So I have a few gates/garage doors that are connected to a Shelly1 to toggle a switch on the controller

GPIO4 - Is the relay that toggles the controller
GPIO5 - is a reed switch that closes when the gate/door is closed

State transitions:
          - CLOSED -> OPENING
          - OPENING -> OPENING_INTERRUPTED
          - OPENING_INTERRUPTED -> CLOSING
          - OPEN -> CLOSING
          - CLOSING -> CLOSING_INTERRUPTED
          - CLOSING_INTERRUPTED -> OPENING

I have a few automations open and closing theses gates/doors and what I'd like is that if the door is closing and another automation sends a CLOSE command, the new CLOSE command is ignored, rather than triggering 'CLOSING_INTERRUPTED'

I have built something using standard espHome template cover using current_operation and delays (10 seconds to close or open), but the delays mean that you can't 'STOP' the gate/door quickly.

Would you have a template for this situation? I tried looking at the example here: https://gist.github.com/muxa/68a6e8f8cdbb734c9e0d06a9b87d0147
but I think your state machine has changed since then as it gives errors about action being deprecated etc.

**Comment by muxa** [comment]
@hoontune I've updated the gist to work with the latest version of the state machine.

**Comment by hoontune** [comment]
Thanks, but I think the gist is emulating the end_stop?  My situation is a little different.

I have no physical buttons for a user to press, everything is handle via HA.

```
substitutions:
  friendly_name: garage2


esphome:
  name: garage2
  platform: ESP8266
  board: esp01_1m

# The door contact sensor that is attached to SW on the 
# Shelly 1. Not exposed to HA, instead used to set the 
# closed state of the cover.
binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: $friendly_name Contact Sensor
    id: contact_sensor
    internal: false
    filters:
      - invert:

# The relay in the Shelly 1 that will deliver the pulse to
# the gate opener (not exposed to HA)
switch:
  - platform: gpio
    pin: GPIO4
    name: $friendly_name Relay
    id: relay
    internal: true

    
# This creates the actual gate in HA. The state is based
# on the contact sensor. Opening/closing the gate simply
# turns the relay on/off with a 0.5s delay in between.
cover:
  - platform: template
    device_class: garage
    name: $friendly_name
    id: template_cov
    lambda: |-
      if (id(contact_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
    close_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
    stop_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay      
```

I need the state machine to handle the closed->opening->open -> closing ->closed but to understand that the Contact Sensor has the final say

I maybe asking too much
