### ISSUE TITLE
Change the order of state.on_enter and transition.action

### ISSUE THREAD

**Issue by GrKoR** [muxa/esphome-state-machine#16]
It seems like an order of state.on_enter handler and transition specific action is incorrect.

Test code:
```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLDOWN_16
    name: "Button #2"
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - state_machine.transition: BTN2_SHORT_CLICK

script:
  - id: filling
    mode: single
    then:
      - delay: 2s
      - state_machine.transition: FILLING_OK

state_machine:
  - name: State Machine
    id: fsm
    initial_state: FSM_STATUS_OK
    states:
      - name: FSM_STATUS_OK
      - name: FSM_IN_PROGRESS
        on_set:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_set handler");'
        on_enter:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_enter handler");'
        on_leave:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_leave handler");'
    inputs:
      - name: BTN2_SHORT_CLICK
        transitions:
          - from: FSM_STATUS_OK
            to: FSM_IN_PROGRESS
            action:
              - lambda: 'ESP_LOGW("BTN2_SHORT_CLICK: FSM_STATUS_OK -> FSM_IN_PROGRESS", "action handler");'
              - script.execute: filling
        action:
          - lambda: 'ESP_LOGW("BTN2_SHORT_CLICK", "action handler");'
      - name: FILLING_OK
        transitions:
          - FSM_IN_PROGRESS -> FSM_STATUS_OK
```

Log output:
```
[18:25:19][D][binary_sensor:036]: 'Button #2': Sending state ON
[18:25:19][D][binary_sensor:036]: 'Button #2': Sending state OFF
[18:25:19][D][state_machine:099]: BTN2_SHORT_CLICK: transitioned from FSM_STATUS_OK to FSM_IN_PROGRESS
[18:25:19][W][FSM_IN_PROGRESS:072]: on_enter handler
[18:25:19][W][BTN2_SHORT_CLICK: FSM_STATUS_OK -> FSM_IN_PROGRESS:082]: action handler
[18:25:19][W][BTN2_SHORT_CLICK:085]: action handler
[18:25:21][D][state_machine:099]: FILLING_OK: transitioned from FSM_IN_PROGRESS to FSM_STATUS_OK
[18:25:21][W][FSM_IN_PROGRESS:074]: on_leave handler
```

Expected sequence of events:
1. Button pressed
2. Input BTN2_SHORT_CLICK processed
3. BTN2_SHORT_CLICK transition-specific action done
4. BTN2_SHORT_CLICK action done
3. State machine state changed
4. State machine state.on_enter called
5. ...
6. State machine state.on_leave called

The actual sequence of events:
1. Button pressed
2. Input BTN2_SHORT_CLICK processed
3. State machine state changed
4. State machine state.on_enter called
5. BTN2_SHORT_CLICK transition-specific action done
6. BTN2_SHORT_CLICK action done
7. ...
8. State machine state.on_leave called

The impact and the result are mixed up. I think the sequence will be significantly more logical if the impact precedes the result.

**Comment by GrKoR** [comment]
@muxa I don't know what version it has =) How can I check it?
I think I use the latest version of state machine (but I'm not sure) cause I use it as external component:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine
```
ESPHome version is `2021.9.3` if it matters.


It seems we have a misunderstanding here. In my example I referred to this sequence:
`transition.on_action -> input.on_action -> new_state.on_enter -> ... -> new_state.on_leave`
Are you talking about on_leave handler of previous state?  Like this:
`prev_state.on_leave -> transition.on_action -> input.on_action -> new_state.on_enter`


> The sequence of calling the action should probably be:
> 
> `on_leave -> transition.on_action -> input.on_action -> on_enter`
If in this case `prev_state.on_leave` and `new_state.on_enter` then I completely agree with you. But my test yaml generates this sequence:
`new_state.on_enter -> transition.on_action -> input.on_action -> new_state.on_leave`
 It looks strange.


> Would it be useful to split the two `on_action` configs into `on_leave` and `on_enter` to allow for more fine-grained control?
Yep. That would be my next suggestion =) The only wish is to name them `before_state` and `after_state`. I think it will be clearer this way.
Thus, the sequence will be as follows:
`prev_state.on_leave -> prev_transition.after_state -> prev_input.after_state -> new_input.before_state -> new_transition.before_state -> new_state.on_enter`

What do you think about it?

**Comment by muxa** [comment]
@GrKoR 

I'm thinking of adding support for conditional transitions in future, so in order to support that I think the following sequence will be more appropriate (I've used `on_before_transition` and `on_after_transition` to make it a bit more semantic):

`prev_transition.on_before_transition -> prev_input.on_before_transition -> prev_state.on_leave -> new_input.on_after_transition -> new_transition.on_after_transition -> new_state.on_enter`

I'm not sure about the order of `new_input` and `new_transition` though...

**Comment by muxa** [comment]
I might fix the callback order first before going too far down the rabbit hole of the new structure of actions.

**Comment by muxa** [comment]
@GrKoR I've pushed a small update:
> 1.0.0-rc.8
> Moved transition/input actions to before on_leave actions

This produces the following output:

```
[20:34:33][D][binary_sensor:036]: 'Button #2': Sending state ON
[20:34:33][D][binary_sensor:036]: 'Button #2': Sending state OFF
[20:34:33][D][state_machine:099]: BTN2_SHORT_CLICK: transitioned from FSM_STATUS_OK to FSM_IN_PROGRESS
[20:34:33][W][BTN2_SHORT_CLICK: FSM_STATUS_OK -> FSM_IN_PROGRESS:054]: transition action handler
[20:34:33][W][BTN2_SHORT_CLICK:057]: input action handler
[20:34:33][W][FSM_STATUS_OK:040]: on_leave handler
[20:34:33][W][FSM_IN_PROGRESS:045]: on_enter handler
[20:34:35][D][state_machine:099]: FILLING_OK: transitioned from FSM_IN_PROGRESS to FSM_STATUS_OK
[20:34:35][W][FSM_IN_PROGRESS:047]: on_leave handler
[20:34:35][W][FSM_STATUS_OK:038]: on_enter handler
```

I've tweaked logging a bit:

```yaml
state_machine:
  - name: State Machine
    id: fsm
    initial_state: FSM_STATUS_OK
    states:
      - name: FSM_STATUS_OK
        on_enter:
          - lambda: 'ESP_LOGW("FSM_STATUS_OK", "on_enter handler");'
        on_leave:
          - lambda: 'ESP_LOGW("FSM_STATUS_OK", "on_leave handler");'
      - name: FSM_IN_PROGRESS
        on_set:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_set handler");'
        on_enter:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_enter handler");'
        on_leave:
          - lambda: 'ESP_LOGW("FSM_IN_PROGRESS", "on_leave handler");'
    inputs:
      - name: BTN2_SHORT_CLICK
        transitions:
          - from: FSM_STATUS_OK
            to: FSM_IN_PROGRESS
            action:
              - lambda: 'ESP_LOGW("BTN2_SHORT_CLICK: FSM_STATUS_OK -> FSM_IN_PROGRESS", "transition action handler");'
              - script.execute: filling
        action:
          - lambda: 'ESP_LOGW("BTN2_SHORT_CLICK", "input action handler");'
      - name: FILLING_OK
        transitions:
          - FSM_IN_PROGRESS -> FSM_STATUS_OK
````

This still changes the current state before calling the actions, but at least the order of actions is more correct now. 

The plan is to split the transition/input actions as illustrated in previous comments.
