### ISSUE TITLE
Add posibility of creating the conditional transitions

### ISSUE THREAD

**Issue by majkrzak** [muxa/esphome-state-machine#38]
I would like to suggest an enhancement, which I fill may be extremely useful.

Adding possibility to specify the `condition` parameter for transitions, like:

```yaml
transitions:
- from: IDLE
  to: SCANNING
  condition:
     lambda: ...
```
