### ISSUE TITLE
Feature Suggestion: Transition Trigger Based on a Timer

### ISSUE THREAD

**Issue by kevdel** [muxa/esphome-state-machine#40]
a suggestion for a feature.. If I could write C++ I would give you a push request :)

Timer Triggered Transitions
1. An optional parameter (max_state_duration) to define how long the state machine can stay in any particular state
2. If no transition received within X seconds of entering a state then, based on the current state, automatically send one of th defined transitions
3. timers get reset on any state change event
4. If there is no transition defined for the current state then the automatic trigger is ignored, timer is reset and the cycle continues

An Example Configuration  with the suggestion integrated

```yaml
state_machine:
  - name: Sauna Controller
    id: sauna_state_machine
    states:
      - "OFF"
      - "ON"
      - "HEATING"
    initial_state: "OFF" 
    max_state_duration: 5400 # timer in seconds
      expiry:  # in this case, the sauna state will automatically switch to OFF after 5400 seconds (mimics the control board on the device)
          state: "HEATING" # if in this state then send the trigger transition
          trigger: power # the transition to trigger after timer expires

    inputs:
      - name: power
        transitions:
          - OFF -> ON
          - ON -> OFF
          - HEATING -> OFF
      - name: heat
        transitions:
          - ON-> HEATING
          - HEATING -> ON
```

**Comment by muxa** [comment]
This should already be possible to achieve with what's available, using `delay`:

```yaml
state_machine:
  - name: Sauna Controller
    id: sauna_state_machine
    states:
      - "OFF"
      - name: "ON"
        on_enter:
          - delay: 5400s
          - state_machine.transition: power
      - name: "HEATING"
        on_enter:
          - delay: 5400s
          - state_machine.transition: power
    initial_state: "OFF" 

    inputs:
      - name: power
        transitions:
          - OFF -> ON
          - ON -> OFF
          - HEATING -> OFF
      - name: heat
        transitions:
          - ON-> HEATING
          - HEATING -> ON
```
